#!/bin/bash

if [ ! -f install ];then
    echo 'install must be run within its container folder' 1>&2
    exit 1    
fi

CURDIR=$(pwd)
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"
#export DELIVERY_CONFIG=$CURDIR"/conf"
#source /etc/profile

gofmt -w src

go install queueup

echo "finish"
